# Hyprland - Task File
- name: Hyprland - Install and Configure
  tags: hyprland-setup

  block:
    - name: Remove existing hypr config files
      ansible.builtin.file:
        state: absent
        path: "{{ hyprland_config_path }}"
    - name: Link hypr config files
      ansible.builtin.file:
        src: "{{ hyprland_config_files.src }}"
        dest: "{{ hyprland_config_files.dest }}"
        state: link
