# Hyprland - Task File
- name: Hyprland - Install and Configure
  tags: hyprland-setup

  block:
    # Base Hyprland setup
    - name: Remove existing hypr config files
      ansible.builtin.file:
        state: absent
        path: "{{ hyprland_config_path }}"
    - name: Link hypr config files
      ansible.builtin.file:
        src: "{{ hyprland_config_files.src }}"
        dest: "{{ hyprland_config_files.dest }}"
        state: link
    # Waybar setup
    - name: Remove existing waybar config files
      ansible.builtin.file:
        state: absent
        path: "{{ waybar_config_path }}"
    - name: Link waybar config files
      ansible.builtin.file:
        src: "{{ waybar_config_files.src }}"
        dest: "{{ waybar_config_files.dest }}"
        state: link 
    # Remove Dolphin because it fucking sucks
    - name: Remove Dolphin
      community.general.pacman:
        name: dolphin
        state: absent
