# Homebrew - Tasks File
- name: Homebrew - Install and Configure
  tags: homebrew-setup

  block:
    - name: Create Hombrew directory
      ansible.builtin.file:
        path: "{{ homebrew_directory }}"
        state: directory
        owner: "{{ user_account }}"
        group: "{{ user_account }}"
        mode: "{{ homebrew_directory_mode }}"
      become: true

# I need to split this install step out so it's idempodent
    - name: Install Homebrew
      ansible.builtin.shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

    - name: Add env variable to shell
      ansible.builtin.lineinfile:
        dest: "{{ ansible_env_shell.dest }}"
        regexp: "{{ ansible_env_shell.regexp }}"
        line: "{{ ansible_env_shell.line }}"

    - name: Install formulae
      community.general.homebrew:
        name: "{{ homebrew_package }}"
        state: present
      loop: "{{ homebrew_packages }}"
      loop_control:
        loop_var: homebrew_package
