# QMK - Tasks File
- name: QMK - Install and Configure
  tags: qmk-setup
  block:
    - name: Run QMK install command
      ansible.builtin.command:
        cmd: curl -fsSL https://install.qmk.fm | sh

