# Kitty - Tasks File

- name: Kitty - Install and Configure
  tags: kitty-setup
  block:
    - name: Remove Existing Kitty Config Folder
      ansible.builtin.file:
        path: "{{ user_account_path }}/.config/kitty"
        state: absent
    
    - name: Link Kitty configuration
      ansible.builtin.file:
        src: "{{ kitty_config.src }}"
        dest: "{{ kitty_config.dest }}"
        state: link

    - name: Install Kitty
      ansible.builtin.shell:
        cmd: "{{ kitty_install_cmd }}"

    - name: Create bin folder
      ansible.builtin.file:
        path: "{{ kitty_bin_folder.path }}"
        state: directory
        owner: "{{ user_account }}"
        mode: "{{ kitty_bin_folder.mode }}"

    - name: Add Kitty and Kitten to PATH
      ansible.builtin.file:
        src: "{{ app_path.src }}"
        dest: "{{ app_path.dest }}"
        owner: "{{ user_account }}"
        group: "{{ user_account }}"
        state: link
      loop: "{{ kitty_app_filepath }}"
      loop_control:
        loop_var: app_path


    - name: Update bashrc to include randomized backgrounds
      ansible.builtin.lineinfile:
        dest: "{{ kitty_bashrc.dest }}"
        regexp: "{{ kitty_bashrc.regexp }}"
        line: "{{ kitty_bashrc.line }}"

# This should be set this way in specific instances. For example this is for Gnome DE's
- name: Set up desktop icons for XDG Desktops
  tags: kitty-icons
  when: ansible_facts['distribution'] == "Linux Mint"
  block:
    - name: Add kitty.desktop to OS Applications
      ansible.builtin.copy:
        src: "{{ shortcut_path.src }}"
        dest: "{{ shortcut_path.dest }}"
        owner: "{{ user_account }}"
        group: "{{ user_account }}"
        mode: a+x
      loop: "{{ kitty_shortcut_filepath }}"
      loop_control:
        loop_var: shortcut_path

    - name: Make XDG-Terminal-Exec use Kitty
      ansible.builtin.shell:
        cmd: "{{ kitty_gnome_terminal }}"

