---
# Kitty - Tasks File

- name: Kitty - Install and Configure
  tags: kitty-configure
  block:
    - name: Install Kitty
      ansible.builtin.shell: "curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin launch=n"

    - name: Add Kitty and Kitten to PATH
      ansible.builtin.file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
      loop: "{{ kitty_linked_directories }}"

    - name: Add kitty.desktop to OS Applications
      ansible.builtin.copy:
        src: "{{ kitty_application_filepath.src }}"
        dest: "{{ kitty_application_filepath.dest }}"

    - name: Debug each matching local directory path
      ansible.builtin.debug:
        msg: "Found local directory: {{ item }}"
      loop: "{{ lookup('fileglob', '~/mournhold/ansible/playbooks/*').splitlines() }}"
      tags:
        - test-directory
