# All - Group Vars File

# True Globals
ohmyposh_theme: 'agnoster'
user_account: "nerevar"
dotconfig_path: "/home/$USER/.config"

# Role - Git
github_repositories:
  mournhold: "https://github.com/Printoiid/mournhold.git"
  Printoiid: "https://github.com/Printoiid/Printoiid.git"

mournhold_path: "/home/$USER/mournhold"
neovim_repo_config_path: "{{ mournhold_path }}/nvim"
kitty_repo_config_path: "{{ mournhold_path }}/kitty"

# Role - Packages
apt_packages:
  - package: "gcc"
  - package: "curl"
  - package: "tar"
  - package: "git"
  - package: "vlc"
  - package: "steam"
  - package: "tree"
  - package: "wget"
  - package: "kdenlive"
  - package: "keepassxc"
  - package: "build-essential"
  - package: "spotify-client"
  - package: "nvidia-driver-580"
  - package: "flameshot"
    version: "12.1.0"
    state: "fixed"

# Role - Homebrew
homebrew_packages:
  - neovim
  - go
  - yt-dlp
  - talosctl
  - terraform
  - k9s
  - argocd
  - helm
