# All - Group Vars File

apt_packages:
  - package: "git"
  - package: "vlc"
  - package: "steam"
  - package: "tree"
  - package: "wget"
  - package: "keepassxc"
  - package: "build-essential"
  - package: "spotify-client"
  - package: "nvidia-driver-580"
  - package: "flameshot"
    version: "12.1.0"
    state: "fixed"

homebrew_install_path: "/home/linuxbrew/.linuxbrew/bin/brew"
homebrew_update: false
homebrew_packages:
  - neovim
  - gcc

github_repositories:
  - name: mournhold
    uri: "https://github.com/Printoiid/mournhold.git"
    dest: "~/mournhold"
  - name: Printoiid
    uri: "https://github.com/Printoiid/Printoiid.git"
    dest: "~/Printoiid"

kitty_curl_url: "https://sw.kovidgoyal.net/kitty/installer.sh"
kitty_install_destination: "~/Downloads/kitty_install.sh"
kitty_validate_certs: true

kitty_linked_directories:
  - src: "~/.local/kitty.app/bin/kitten"
    dest: "~/.local/bin/kitten"
  - src: "~/.local/kitty.app/bin/kitty"
    dest: "~/.local/bin/kitty"

kitty_application_filepath:
  src: "~/.local/kitty.app/share/applications/kitty.desktop/"
  dest: "~/.local/share/applications/"
