# Fonts - Tasks File
- name: Fonts - Install and Configure
  tags: fonts-setup
  block:
    - name: Link Fonts
      ansible.builtin.file:
        src: "{{ font_src }}"
        dest: "{{ font_dest }}"
        state: link
