# Packages - Defaults File
apt_packages:
  - package: ""
    version: "*"
    state: "latest"
    allow_downgrade: false
    autoclean: true

bin_executable:
  dest: ~/.bashrc
  regexp: /.local/bin:$PATH
  line: export PATH="$HOME/.local/bin:$PATH"
