# Directories - Tasks File
- name: Create folders and files for downloaded archives and modifications
  tags: modification-setup
  when: ansible_facts['pkg_mgr'] == 'apt'
  block:
    - name: Create hidden .packages folder for downloaded archives
      ansible.builtin.file:
        dest: "/home/{{ user_account }}/.packages/"
        state: directory
        mode: '0777'
        # This needs to be updated later
        # The fuck am I using this for again????
