# Hyprland - Default File

base_hyprland_directory: "{{ dotconfig_path }}/hypr"
hyprland_config_files: 
  - src: "{{ hyprland_repo_config_path }}/hyprland.conf"
    dest: "{{ base_hyprland_directory }}/hyprland.conf"
