# Kitty - Default File
kitty_install_cmd: "curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin launch=n"
kitty_asset_path: "{{ mournhold_path }}/ansible/playbooks/roles/kitty"

kitty_config:
  src: "{{ kitty_asset_path }}/config"
  dest: "{{ dotconfig_path }}/kitty"

kitty_bashrc:
  dest: "{{ bashrc_path }}"
  regexp: 'alias kitty=kitty --override background_image'
  line: 'alias kitty="kitty --override background_image_layout=cscaled --override background_image=$(ls {{ user_account_path }}/.config/kitty/img/*.png | sort --random-sort | head -1)"'

kitty_bin_folder:
  path: "{{ user_account_path }}/.local/bin/"
  mode: '0775'

kitty_app_filepath:
  - src: ~/.local/kitty.app/bin/kitten
    dest: ~/.local/bin/kitten
  - src: ~/.local/kitty.app/bin/kitty
    dest: ~/.local/bin/kitty

kitty_shortcut_filepath:
  - src: ~/.local/kitty.app/share/applications/kitty-open.desktop
    dest: ~/.local/share/applications/kitty-open.desktop
  - src: ~/.local/kitty.app/share/applications/kitty.desktop
    dest: ~/.local/share/applications/kitty.desktop

# Update Icons
xdg_terminals: "{{ user_account_path }}/.config/xdg-terminals.list"
kitty_gnome_terminal: "echo 'kitty.desktop' > {{ user_account_path }}/.config/xdg-terminals.list"

