# OhMyPosh - Defaults File
ohmyposh:
  url: https://ohmyposh.dev/install.sh
  dest: "{{ mournhold_path }}/ansible/playbooks/roles/ohmyposh/scripts/ohmyposh.sh"

ohmyposh_bash:
  dest: "{{ bashrc_path }}"
  regexp: oh-my-posh
  line: eval "$(oh-my-posh init bash --config "{{ ohmyposh_theme }}")"
