# Neovim - Tasks File
- name: Neovim - Install and Configure
  tags: neovim-setup
  block:
    - name: Link Neovim Configuration
      ansible.builtin.file:
        src: "{{ neovim_repo_config_path }}"
        dest: "{{ dotconfig_path }}/nvim"
        state: link
