# Github - Tasks File
- name: Github Repositories - Install and Configure
  tags: ghrepo-setup
  block:
    - name: Loop and clone listed Github repositories
      ansible.builtin.git:
        repo: "{{ repo.uri }}"
        dest: "{{ repo.dest | default('/home/$USER/{{ repo.name }}') }}"
      loop: "{{ github_repositories }}"
      loop_control:
        loop_var: repo
