# Github - Tasks File
- name: Github Repositories - Install and Configure
  tags: ghrepo-setup
  block:
    - name: Loop and clone listed Github repositories
      ansible.builtin.git:
        repo: "{{ repo.uri }}"
        dest: "/home/$USER/{{ repo.name }}"
      loop: "{{ github_repositories | dict2items(key_name='name', value_name='uri') }}"
      loop_control:
        loop_var: repo
