# Linux - Playbook
- hosts: vvardenfell
  vars_files:
    - ../inventory/group_vars/password.yml
  connection: local
  tasks:
    - name: Show machine Facts
      ansible.builtin.debug:
        var: ansible_facts
        verbosity: 2

    - name: Display OS Information
      ansible.builtin.debug:
        verbosity: 1
        msg:
          - "---------------------------------"
          - "It's just nice to have, okay Rob?"
          - "---------------------------------"
          - "Verbosity: {{ ansible_verbosity }}"
          - "Distribution: {{ ansible_facts['distribution'] }}"
          - "Variety: {{ ansible_facts['distribution_file_variety'] }}"
          - "Package Manager: {{ ansible_facts['pkg_mgr'] }}"
          - "Version: {{ ansible_facts['distribution_version'] }}"
          - "System: {{ ansible_facts['system'] }}"
          - "Hosts: {{ ansible_play_hosts }}"

- name: Import and execute the Packages Playbook
  ansible.builtin.import_playbook: packages.yml

- name: Import and execute the Files Playbook
  ansible.builtin.import_playbook: files.yml

- name: Import and execute the Directories Playbook
  ansible.builtin.import_playbook: directories.yml

- name: Import and execute the Fonts Playbook
  ansible.builtin.import_playbook: fonts.yml

- name: Import and execute the Homebrew Playbook
  ansible.builtin.import_playbook: homebrew.yml

- name: Import and execute the Neovim Playbook
  ansible.builtin.import_playbook: neovim.yml

- name: Import and execute the Kitty Playbook
  ansible.builtin.import_playbook: kitty.yml

- name: Import and execute the OhMyPosh Playbook
  ansible.builtin.import_playbook: ohmyposh.yml

- name: Import and execute the Fonts Playbook
  ansible.builtin.import_playbook: fonts.yml
  when: ansible_facts['distribution'] == 'Linux Mint'

- name: Import and execute the Hyprland Playbook
  ansible.builtin.import_playbook: hyprland.yml
  when: ansible_facts['distribution'] == 'Archlinux'

- name: Import and execute the QMK Playbook
  ansible.builtin.import_playbook: qmk.yml
  when: ansible_facts['distribution'] == 'Archlinux'

- name: Import and execute the Rofi Playbook
  ansible.builtin.import_playbook: rofi.yml
  when: ansible_facts['distribution'] == 'Archlinux'
