# Prevent multiple instances of hyprlock
general {
	lock_cmd = pidof hyprlock || hyprlock
}
# Dim the screen more after 1 minute(s)
listener {
	timeout = 60
	on-timeout = brightnessctl -s set 50
	on-resume = brightnessctl -r
}
# Lock the OS after 5 minute(s)
listener {
	timeout = 300
	on-timeout = hyprlock
}
# Suspend the battery after 10 minute(s)
listener {
	timeout = 600
	on-timeout = systemctl suspend
}
