# Lock Screen Configuration
# ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#general-remarks
$font = Magic Cards
$color1 = rgba(5,25,35,1) # Ink Black
$color1_opaque = rgba(5,25,35,0.8) # Ink Black
$color2 = rgba(0,53,84,1) # fade_on_empty Space Blue
$color3 = rgba(0,100,148,1) # Baltic Blue
$color4 = rgba(5,120,202,1) # Steel Blue
$color5 = rgba(0,166,251,1) # Fresh Sky 
$color6 = rgba(251,85,0,1) # Blaze Orange
$primaryMonitor = DP-1

general {
    hide_cursor = false
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = screenshot
    blur_passes =  2
}

input-field {
    monitor = $primaryMonitor
    size = 20%, 6%
    outline_thickness = 3
    inner_color = $color1_opaque # Opaque Ink Black

    outer_color = $color5 $color6 30deg
    check_color = rgba(00ff99ee) rgba(ff6633ee) 120deg
    fail_color = rgba(ff6633ee) rgba(ff0066ee) 40deg

    font_color = rgb(143, 143, 143)
    fade_on_empty = false
    rounding = 15

    font_family = $font
    placeholder_text = Come Nerevar, friend or traitor, come
    fail_text = $PAMFAIL

    # uncomment if you wish to display a message during authentication
    # check_text = Authenticating...

    # uncomment to use a letter instead of a dot to indicate the typed password
    # dots_text_format = *
    # dots_size = 0.4
    dots_spacing = 0.3

    # uncomment to use an input indicator that does not show the password length (similar to swaylock's input indicator)
    # hide_input = true

    position = 0, 0
    halign = center
    valign = center
}

# TIME
label {
    monitor = $primaryMonitor
    text = $TIME # ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#variable-substitution
    font_size = 90
    font_family = $font

    position = 0, 120
    halign = center
    valign = center
}

# DATE
label {
    monitor = $primaryMonitor
    text = cmd[update:60000] date +"%A, %d %B %Y" # update every 60 seconds
    font_size = 25
    font_family = $font

    position = 0, 60
    halign = center
    valign = center
}
