# Packages - Tasks File
- name: APT Packages - Install and Configure
  tags: packages-setup
  when: ansible_facts['pkg_mgr'] == "apt"
  block:
    - name: Loop and install listed APT packages
      ansible.builtin.apt:
        autoclean: "{{ apt_package.autoclean | default('true') }}"
        allow_downgrade: "{{ apt_package.allow_downgrade | default('false') }}"
        name: "{{ apt_package.package }}=*{{ apt_package.version | default('*') }}*"
        state: "{{ apt_package.state | default('latest') }}"
      loop: "{{ apt_packages }}"
      loop_control:
        loop_var: apt_package

- name: Pacman Packages - Install and Configure
  tags: packages-setup
  when: ansible_facts['pkg_mgr'] == "pacman"
  block:
    # Pacman Libary change
    - name: Uncomment [multilib] in /etc/pacman.conf
      ansible.builtin.replace:
        path: "{{ pacman_multilib.path }}"
        regexp: "{{ pacman_multilib.regexp }}"
        replace: "{{ pacman_multilib.replace }}"
      become: true
    # Update the cache
    - name: Update Pacman to include new libaries
      community.general.pacman:
        update_cache: true
    # Install all listed packages
    - name: Loop and install listed Pacman packages
      community.general.pacman:
        name: "{{ pacman_package.package }}"
        state: "{{ pacman_package.state | default('latest') }}"
      loop: "{{ pacman_packages }}"
      loop_control:
        loop_var: pacman_package
