# Packages - Tasks File
- name: Packages - Install and Configure
  tags: packages-setup
  block:
    - name: Loop and install listed APT packages
      ansible.builtin.apt:
        autoclean: "{{ apt_package.autoclean | default('true') }}"
        allow_downgrade: "{{ apt_package.allow_downgrade | default('false') }}"
        name: "{{ apt_package.package }}=*{{ apt_package.version | default('*') }}*"
        state: "{{ apt_package.state | default('latest') }}"
      loop: "{{ apt_packages }}"
      loop_control:
        loop_var: apt_package
  when: ansible_facts["ansible_pkg_mgr"] == "apt"

  block:
    - name: Loop and install listed Pacman packages
      community.general.pacman:
        name: "{{ pacman_packages.package }}"
        state: "{{ pacman_packages.state | default('latest') }}"
      loop: "{{ pacman_packages }}"
      loop_control:
        loop_var: pacman_packages
  when: ansible_facts["ansible_pkg_mgr"] == "pacman"

  block:
    - name: Add ~/.local/bin/* to executable in $PATH
      ansible.builtin.lineinfile:
        dest: "{{ bin_executable.dest }}"
        regexp: "{{ bin_executable.regexp }}"
        line: "{{ bin_executable.line }}"

    - name: Create hidden .packages folder for downloaded archives
      ansible.builtin.file:
        dest: "/home/$USER/.packages/"
        state: directory
        mode: '0777'
        # This needs to be updated later
        # The fuck am I using this for again????
